language: C
dist: trusty
env:
  global:
    - CI40_SDK="OpenWrt-SDK-0.10.4-pistachio-marduk_gcc-5.3.0_musl-1.1.14.Linux-x86_64"
    - CI40_SDK_URL="https://downloads.creatordev.io/pistachio/marduk/"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gnupg git-core build-essential libssl-dev libncurses5-dev unzip gawk subversion mercurial
script:
  - mkdir -p $HOME/build/letmecreatefeed/letmecreate && ln -s $TRAVIS_BUILD_DIR $HOME/build/letmecreatefeed/letmecreate/LetMeCreate
  - cp $TRAVIS_BUILD_DIR/miscellaneous/Makefile.devel $HOME/build/letmecreatefeed/letmecreate/Makefile
  - cp $TRAVIS_BUILD_DIR/miscellaneous/Config.in.devel $HOME/build/letmecreatefeed/letmecreate/Config.in
  - export CI40_FILE_URL="$CI40_SDK_URL$CI40_SDK.tar.bz2"
  - echo $CI40_FILE_URL
  - cd $HOME/build && wget $CI40_FILE_URL && tar xfj $CI40_SDK.tar.bz2
  - cd $CI40_SDK && echo src-link custom $HOME/build/letmecreatefeed/ >> feeds.conf.default
  - ./scripts/feeds update -a && ./scripts/feeds install -a
  - make package/letmecreate/compile -j1 V=s
